export const SEARCH_WORD_SUCCESS = "SEARCH_WORD_SUCCESS"
export const SEARCH_WORD_FAILURE = "SEARCH_WORD_FAILURE"
export const CLEAR_SEARCH = "CLEAR_SEARCH"
export const ADD_TO_HISTORY = "ADD_TO_HISTORY"